# While going for production change host to 52.77.131.42
elasticsearchHost: 52.77.131.42
elasticPort: 9300
# While going for production change cluster name to MK-NEW-CLUSTER
clusterName: MK-NEW-CLUSTER

productElasticsearchHost: 52.74.202.15
productElasticPort: 9300
productClusterName: MK-FRONT-ALL

# While going for production change host to 54.169.206.4
redisHost: 54.169.206.4
redisPort: 6379
redisPassword: stage@redis_caching

apiAuthenticationDatabase:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: root
    # the password
    password: stage@mebelkart
    # the JDBC URL; the database is called DWGettingStarted
    url: jdbc:mysql://54.169.206.4:3306/mk_api
mebelkartProductionDatabase:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: root
    # the password
    password: stage@mebelkart
    # the JDBC URL; the database is called DWGettingStarted
    #convertToNull is to handle date requests which contains all zeros
    url: jdbc:mysql://54.169.206.4:3306/mebelkart_prod?zeroDateTimeBehavior=convertToNull
server:
  applicationConnectors:
    - type: http
      port: 8000
    - type: https
      port: 8443
      keyStorePath: front-api/src/main/resources/mkapi.keystore
      keyStorePassword: vinit@18
      validateCerts: false
      validatePeers: false    
  adminConnectors:
    - type: http
      port: 8001
    - type: https
      port: 8444
      keyStorePath: front-api/src/main/resources/mkapi.keystore
      keyStorePassword: vinit@18
      validateCerts: false
      validatePeers: false
logging:
  level: INFO
  loggers:
    # Sets the level for 'com.mebelkart.api' to DEBUG.
    com.mebelkart.api: INFO
  appenders:
    - type: console
    - type: file
      threshold: ALL
      logFormat: "%-6level [%d{yyyy-MM-dd_HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: log.out
      archivedLogFilenamePattern: log-%d{yyyy-MM-dd}-%i.out.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB
