database1:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: root
    # the password
    password: root
    # the JDBC URL; the database is called DWGettingStarted
    url: jdbc:mysql://localhost:3306/mk_api
database2:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: root
    # the password
    password: root
    # the JDBC URL; the database is called DWGettingStarted
    url: jdbc:mysql://localhost:3306/mebelkart_prod
server:
  applicationConnectors:
    - type: http
      port: 8080
#      keyStorePath: src/main/resources/mkapi.keystore
#      keyStorePassword: vinit@18
#      validateCerts: false
#      validatePeers: false
  adminConnectors:
    - type: http
      port: 8081
#      keyStorePath: src/main/resources/mkapi.keystore
#      keyStorePassword: vinit@18
#      validateCerts: false
#      validatePeers: false
