database1:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: root
    # the password
    password: root
    # the JDBC URL; the database is called DWGettingStarted
    url: jdbc:mysql://localhost:3306/mk_api
database2:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: root
    # the password
    password: root
    # the JDBC URL; the database is called DWGettingStarted
    url: jdbc:mysql://localhost:3306/mebelkart_prod
server:
  applicationConnectors:
    - type: http
      port: 8080
    - type: https
      port: 8443
      keyStorePath: front-api/src/main/resources/mkapi.keystore
      keyStorePassword: vinit@18
      validateCerts: false
      validatePeers: false    
  adminConnectors:
    - type: http
      port: 8081
    - type: https
      port: 8444
      keyStorePath: front-api/src/main/resources/mkapi.keystore
      keyStorePassword: vinit@18
      validateCerts: false
      validatePeers: false
logging:
  level: INFO
  loggers:
    # Sets the level for 'com.mebelkart.api' to DEBUG.
    com.mebelkart.api: WARN
  appenders:
    - type: console
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{yyyy-MM-dd_HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: log.out
      archivedLogFilenamePattern: log-%d{yyyy-MM-dd}-%i.out.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MB