package com.mebelkart.api.admin.v1.core;

public class Admin {
	/**
     * Entity's unique identifier.
     */
    private int id;
    /**
     * a_user_name.
     */    
    private String a_user_name;
    
    /**
     * a_password.
     */    
    private String a_password;
    
    /**
     * product a_admin_level.
     */
    private int a_admin_level;
    
    public Admin() {
    }
    /**
     * A constructor to create Products. Id is not passed, cause it's
     * auto-generated by RDBMS.
     *
     */
    public Admin(int id,String a_user_name, String a_password, int a_admin_level) {
    	this.setId(id);
    	this.setA_user_name(a_user_name);
    	this.setA_password(a_password);
    	this.setA_admin_level(a_admin_level);        
    }
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getA_user_name() {
		return a_user_name;
	}
	public void setA_user_name(String a_user_name) {
		this.a_user_name = a_user_name;
	}
	public String getA_password() {
		return a_password;
	}
	public void setA_password(String a_password) {
		this.a_password = a_password;
	}
	public int getA_admin_level() {
		return a_admin_level;
	}
	public void setA_admin_level(int a_admin_level) {
		this.a_admin_level = a_admin_level;
	}
	
}
